### ISSUE TITLE
w32explore函数中使用w32-shell-excute调用了“explore”，但是windows中并不存在，是如何工作的？

### ISSUE THREAD

**Issue by silaoA** [jixiuf/vmacs#2]
https://github.com/jixiuf/vmacs/blob/65417ab36f22d45ec864d946deceab40688a16d3/lazy/lazy-open-in-file-manager.el#L23
如题。
另，在我的Emacs上（Windows 10 64bit，GNU Emacs 28.2），`convert-standard-filename`没能把路径符"/"转换成"\"，explorer.exe只能支持"\"。

**Comment by jixiuf** [comment]
我很久没用windows 了， 还是使用xp 时期弄的配置。
